// <auto-generated />
using DatosEEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatosEEF.Migrations
{
    [DbContext(typeof(EEFContext))]
    [Migration("20220926175240_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DatosEEF.Telefono", b =>
                {
                    b.Property<string>("Ntelefono")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("ntelefono");

                    b.Property<string>("Direccion")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(240)
                        .IsUnicode(false)
                        .HasColumnType("varchar(240)")
                        .HasColumnName("observaciones");

                    b.HasKey("Ntelefono")
                        .HasName("PK__telefono__F9137AFE1B6AFC39");

                    b.ToTable("telefonos");
                });
#pragma warning restore 612, 618
        }
    }
}
